README.md, conf/float-rt.conf, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF
When we use s3fs, sometimes the task finished but the result file
has not been synchronized to the local system. In the check
status function, we should make sure all the file (including
.command.out, .command.std, .exitcode) are available before we mark the task completes.
=> [GH-13] check `.exitcode` in output dir.

README.md, conf/float-rt.conf, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF
The `s3fs` doesn't update the directory cache unless we issue a read opration to the directory.
In the plugin, call list directory before we check the existance of the required files.
Upgrade the version to 0.1.6
=> [GH-4] List the dir. before we check files.

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Mapping `Floating` status to `RUNNING` to align with the process lifecycle in Nextflow.
=> [GH-18] Mapping `Floating` to `RUNNING`.

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy
If the workflow contains a bin directory, upload to a tmp directory in the working directory.
In `.command.run` script, we add `export PATH=...` to include the tmp directory.
=> [GH-32] Upload bin directory.

README.md
The example in README does not properly set the property of process.
Since we have support the process configuration, change the sample to align to the DSL syntax.
=> [GH-28] Correct syntax in README.

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Enable the plugin to read credentials from the environment variable:
* MMC_ADDRESS: address of the op center
* MMC_USERNAME: login username
* MMC_PASSWORD: login password
Hide the password in the log.
Add samples in the README to illustrate how to input the credentials with NextFlow secrets.
=> [GH-29] Read credentials from ENV or secrets.

plugins/nf-float/src/main/com/memverge/nextflow/CmdResult.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/test/com/memverge/nextflow/CmdResultTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorMultiOCTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
For now, we use the name of the job to track the ownership of the job. But many user want to give their own job names.
It's better to use the tag to track the source of the job. And user could always add more tags for their own usage.
Add `nf-job-id` tag to track the nf task info.
=> [GH-38] Track job with tags

plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
When user set `docker.registry` or `podman.registry`, use this registry as the default registry.
Use the default registry configured by MMC if they are not available.
=> [GH-37] Support default registry.

plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
The configuration in the float is overwritten by the configuration in the process section.  When the configuration in process is empty, the float address becomes missing.
Do not parse the `process` scope because it is available in the task config.
=> [GH-41] float conf becomes invalid.

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatConfTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Close #27 
This PR adds support for the following process directives:
- disk
- machineType
- resourceLabels
- time
While the CLI options can already be specified via `float.commonExtra`, the process directives are more user-friendly and can also be applied on a per-process level.
Also adds custom config options for `--vmPolicy` and `--migratePolicy`, since these options are some of the most valuable parts of Float but also have the most complicated syntax, we should try to make them as user-friendly as possible.
I also added a few default labels for things like process name, task name, session ID, etc. But feel free to remove them if you don't think they are needed. I copied them from the K8s executor.
I added unit tests for these options but haven't tested them end to end. Let me know if …
=> Add support for several process directives

plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Extra options can be supplied as an array.  The option value may contain space. It would break the command if it was added in the `extraCommon` option directly.
Add that option support the `float` scope.
Closes GH-54.
=> [GH-54] Support `extraOptions` of float

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
One task in the full test profile of nf-core/sarek keeps reporting timeout. To work around this issue, add an extra `timeFactor` to scale the default timeout for the MMC platform.
Closes GH-56.
=> [GH-56] add `timeFactor` in float conf.

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy
For some shared file system, we need to refresh the work directory before we access the files in this folder.  The refresh operation makes sure the content of the folder is updated.
=> Refresh the workDir if not empty.

plugins/nf-float/src/main/com/memverge/nextflow/FloatBin.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/Global.groovy
Sync the float binary with the opcenter when the plugin started.
=> sync the float binary.

plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJob.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatTaskHandler.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatJobTest.groovy
* Add the `cpuFactor` and `memoryFactor` option to tune the settings.
* Unify the code of process job status.
* Properly handle the quoted parameters.
=> Add multiple enhancements.

plugins/nf-float/src/main/com/memverge/nextflow/FloatBin.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/Global.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatConfTest.groovy
Use could use `float login` to generate the credentials file. In this case, the credentials are not required in the nextflow configuration file.
=> Allow user to omit credentials.

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatTaskHandler.groovy
WaveRider may take extra time for migration.  So we should normally include time factor in the configuration file.
Also add more log for job status updates.
=> Update readme to add timeFactor in conf

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy
For nextflow jobs, we should disable MMC re-run by default. Because MMC re-run will start in the same directory and may contain files for the last run. We should utilize the re-run of Nextflow instead.
Bump version to 0.4.2
=> [GH-72] Disable `re-run` by default.

plugins/nf-float/src/main/com/memverge/nextflow/FloatBin.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatJobs.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatConfTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorMultiOCTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
The old implementation list all jobs in the opCenter which is unnecessary.  We should only focus on the job submitted by the plugin.
Remove the full poll in the queue status update.  Add the job entry when we submit it.
Remove the code related to the full job poll and clean up the logs.
=> [GH-75] Too many `put xxx into map` log

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/main/com/memverge/nextflow/Global.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatConfTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/GlobalTest.groovy
aws s3 can authorize a user with key/secret/token. Need to pass token to MMC when user specified for s3 access.
=> [GH-77] Support s3 token authorization

README.md
aws s3 can authorize a user with key/secret/token. Need to pass token to MMC when user specified for s3 access.
=> [GH-77] Update the readme for s3 token

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
As suggested in https://github.com/MemVerge/nf-float/issues/69, it's not a common practice to use `extra = 'xxx'` in a process.
Allow user to specify extra options in `process.ext.float`.
=> [GH-69] Support `float` in `ext` directive`.

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatConf.groovy, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Add a `ignoreTimeLimits` option in float and default to true. If user want to enable time limit, he/she needs to explicitly set this option to `false`.
=> [GH-63] Ignore the time limit by default.

plugins/nf-float/src/main/com/memverge/nextflow/FloatJob.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Log the output of the submit command when we failed to parse job ID for further analysis.
=> [GH-87] Log parsing error for job ID

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
When user does not specify a disk size and the (total input size * 5) is smaller than 6 GB, we should not hard code the disk size to 6 GB. Instead, we should allow MMC to calculate the disk size.
=> [GH-89] Use default disk size of MMC

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy
As title.  If scratch is not specified, default to true and set the stage in strategy to copy to avoid symbolic link between local filesystem and s3fs.
=> [GH-91] default file stage in strategy to copy

README.md, plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
For local work directory, do not change the default scratch option.
=> [GH-95] Do not enable `scratch` for local workdir

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF, plugins/nf-float/src/test/com/memverge/nextflow/GlobalTest.groovy
When we update the LD_LIBRARY_PATH, it may also affect the user executables.
So instead of updating the environment variable, use a function to redirect the call to our aws cli when it is not found in the path.
=> [FLOAT-4537] Failed to execute user binary.

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy
When user does not specify scratch = true specifically, we failed to add the volume option. We should also check if work directory is network based and scratch is not specified.
=> [GH-99] Add volume size for default scratch option

README.md
200 max connection may sometimes cause network error for aws client. Reduce the `maxConnections` property in the sample to 20.
=> update sample configuration for aws.

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
Closes #106 
No task can be submitted with a Mem/CPU ratio < 2 as each task gets its own instance on MM Cloud. Such instances are not available on AWS and that leads to task submission failure.
The applied fix applies a lower bound to the memory spec. of a task based on its CPU spec. If the memory spec. is lower than 2 x CPU spec., it is bumped to 2 x CPU.
I have not applied a version bump to the plugin. I was not sure of the release workflow.
Thank you!
P.S.
A more sophisticated/conservative lower bound is also possible such as,
```groovy
int maxMemGiga = Math.max( (floatConf.maxMemoryFactor * memGiga.doubleValue()).intValue(), cpu * 2 )
```
This approach ensures that at least the upper limit of the memory is always greater or equal to  2 x CPU. But this strategy shrinks the permissible …
=> [GH-106][PER-9] Fixed an issue where an unusual mem spec caused the task submission to fail

plugins/nf-float/src/main/com/memverge/nextflow/FloatGridExecutor.groovy, plugins/nf-float/src/resources/META-INF/MANIFEST.MF, plugins/nf-float/src/test/com/memverge/nextflow/FloatBaseTest.groovy, plugins/nf-float/src/test/com/memverge/nextflow/FloatGridExecutorTest.groovy
With this change, users can request for a GPU machine by simply specifying the accelerator directive such as,
```groovy
process {
withName: 'PARABRICKS_FQ2BAMMETH' {
accelerator = 1
}
}
```
nf-float will translate that into `float submit ... --gpu-count 1 ...`
=> [GH-105] Added support for the accelerator directive
